# Generated by Django 5.0 on 2023-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='message',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
