# Generated by Django 5.0 on 2023-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_forms_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_email', models.CharField(max_length=100)),
                ('Emp_msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='forms',
        ),
    ]
