# Generated by Django 5.0 on 2023-12-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_emp_delete_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='Emp_msg',
            new_name='Emp_password',
        ),
    ]
